=== rafabertholdo/AionEmu2.7/docker-gs/AL-Game/data/static_data/staticdoors/staticdoor_templates.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../global_types.xsd"/>
	<xs:include schemaLocation="../import.xsd"/>
	<xs:element name="staticdoor_templates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="world" type="World" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="World">
		<xs:sequence>
			<xs:element name="staticdoor" type="StaticDoor" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="world" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="StaticDoor">
		<xs:attribute name="x" type="xs:float"/>
		<xs:attribute name="y" type="xs:float"/>
		<xs:attribute name="z" type="xs:float"/>
		<xs:attribute name="doorid" type="xs:int"/>
		<xs:attribute name="keyid" type="xs:int"/>
		<xs:attribute name="mesh" type="xs:string"/>
		<xs:attribute name="state" type="xs:string"/>
	</xs:complexType>
</xs:schema>

=== rafabertholdo/AionEmu2.7/docker-gs/AL-Game/data/static_data/staticdoors/staticdoor_templates.xml
<?xml version="1.0" encoding="utf-8"?>
<staticdoor_templates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="staticdoor_templates.xsd">
	<world world="300040000">
		<staticdoor keyid="1" doorid="33" x="1215.4194" y="414.25677" z="142.50447" mesh="idlf1_door.cga" state="0x2" />
	</world>
	<world world="300080000">
		<staticdoor doorid="60" x="257.67542" y="437.25256" z="366.67929" mesh="ab_low_door.cga" state="0xA" />
		<staticdoor doorid="61" x="236.74339" y="494.72775" z="366.67929" mesh="ab_low_door.cga" state="0xA" />
		<staticdoor doorid="63" x="226.06877" y="554.94531" z="366.67929" mesh="ab_low_door.cga" state="0xA" />
		<staticdoor doorid="64" x="226.00847" y="616.10052" z="366.67929" mesh="ab_low_door.cga" state="0xA" />
		<staticdoor doorid="65" x="236.72144" y="676.25885" z="366.67929" mesh="ab_low_door.cga" state="0xA" />
		<staticdoor doorid="66" x="257.59821" y="733.71478" z="366.67929" mesh="ab_low_door.cga" state="0xA" />
	</world>
	<world world="300100000">
		<staticdoor keyid="185000044" doorid="39" x="454.92999" y="530.87" z="953.46997" mesh="shulack_keydoor_01a.cga" state="0xA" />
		<staticdoor keyid="185000043" doorid="43" x="374.04999" y="490.34" z="948.56" mesh="shulack_keydoor_01a.cga" state="0xA" />
		<staticdoor keyid="185000048" doorid="70" x="342.95001" y="464.48001" z="898.90997" mesh="shulack_keydoor_01a.cga" state="0xA" />
		<staticdoor keyid="185000054" doorid="73" x="411.75" y="552.21997" z="947.85999" mesh="shulack_keydoor_01a.cga" state="0xA" />
		<staticdoor keyid="185000042" doorid="74" x="333.17001" y="546.15002" z="953.75" mesh="shulack_keydoor_01a.cga" state="0xA" />
		<staticdoor keyid="185000045" doorid="75" x="539.22998" y="501.04001" z="953.65002" mesh="shulack_keydoor_01a.cga" state="0xA" />
		<staticdoor keyid="185000051" doorid="80" x="699.87665" y="478.4967" z="869.55444" mesh="shulack_keydoor_01a.cga" state="0xA" />
		<staticdoor keyid="185000074" doorid="91" x="712.25" y="531.28998" z="1014.88" mesh="shulack_keydoor_01a.cga" state="0xA" />
		<staticdoor keyid="185000053" doorid="93" x="638.90002" y="470.87" z="1032.89" mesh="shulack_keydoor_01a.cga" state="0xA" />
		<staticdoor keyid="185000049" doorid="94" x="534.96002" y="441.5" z="884.15002" mesh="shulack_keydoor_01a.cga" state="0xA" />
	</world>
	<world world="300110000">
		<staticdoor keyid="185000039" doorid="17" x="408.37442" y="183.5789" z="438.10223" mesh="dreadgion_door.cga" state="0x4" />
		<staticdoor keyid="185000039" doorid="18" x="562.40637" y="183.64265" z="438.13846" mesh="dreadgion_door.cga" state="0x4" />
		<staticdoor keyid="185000040" doorid="40" x="380.40967" y="697.48608" z="401.8692" mesh="dreadgion_prison.cga" state="0x6" />
		<staticdoor keyid="185000072" doorid="44" x="589.62488" y="697.55103" z="401.8692" mesh="dreadgion_prison.cga" state="0x6" />
		<staticdoor keyid="185000072" doorid="45" x="592.40564" y="704.30707" z="402.16504" mesh="dreadgion_prison.cga" state="0x6" />
		<staticdoor keyid="185000072" doorid="46" x="591.4176" y="711.60742" z="401.78061" mesh="dreadgion_prison.cga" state="0x6" />
		<staticdoor keyid="185000040" doorid="47" x="378.84332" y="712.07446" z="401.78061" mesh="dreadgion_prison.cga" state="0x6" />
		<staticdoor keyid="185000040" doorid="48" x="377.75806" y="704.72919" z="402.16504" mesh="dreadgion_prison.cga" state="0x6" />
	</world>
	<world world="300120000">
		<staticdoor keyid="185000062" doorid="1" x="554.29626" y="195.14357" z="179.38689" mesh="ab_up3_naga.cga" state="0xA" />
		<staticdoor keyid="185000061" doorid="2" x="501.4325" y="194.11539" z="179.23265" mesh="ab_up3_lizard.cga" state="0xA" />
		<staticdoor keyid="185000063" doorid="3" x="525.50836" y="241.17401" z="179.16214" mesh="ab_up3_drakan.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="11" x="541.91925" y="881.67035" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000065" doorid="14" x="577.89093" y="845.23376" z="199.34164" mesh="ab_up3_door_04a.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="15" x="528.61566" y="883.95972" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="17" x="515.25275" y="881.57562" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="18" x="503.57059" y="874.97156" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="19" x="495.0369" y="864.69568" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="20" x="490.29245" y="852.11682" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="28" x="490.27402" y="838.50385" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="74" x="494.88986" y="825.87891" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="76" x="553.53674" y="874.79498" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="79" x="562.11761" y="864.52332" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000064" doorid="80" x="566.67206" y="851.99854" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
	</world>
	<world world="300130000">
		<staticdoor keyid="185000067" doorid="1" x="554.13751" y="194.80313" z="179.28378" mesh="ab_up3_naga.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="2" x="541.50482" y="881.35974" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="3" x="528.20135" y="883.72211" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="5" x="514.95459" y="881.43506" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="6" x="503.20822" y="874.72076" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000066" doorid="9" x="501.40955" y="194.15512" z="179.23265" mesh="ab_up3_lizard.cga" state="0xA" />
		<staticdoor keyid="185000068" doorid="10" x="525.18152" y="241.1727" z="179.22443" mesh="ab_up3_drakan.cga" state="0xA" />
		<staticdoor keyid="185000070" doorid="14" x="577.49182" y="845.16333" z="199.34164" mesh="ab_up3_door_04a.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="17" x="494.55392" y="864.5708" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="18" x="489.97031" y="851.83215" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="28" x="489.89212" y="838.30884" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="74" x="494.53024" y="825.64215" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="76" x="553.11902" y="874.65997" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="79" x="561.7348" y="864.30389" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000069" doorid="80" x="566.28241" y="851.64075" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
	</world>
	<world world="300140000">
		<staticdoor keyid="185000057" doorid="1" x="554.00104" y="194.81346" z="179.32158" mesh="ab_up3_naga.cga" state="0xA" />
		<staticdoor keyid="185000056" doorid="2" x="501.3952" y="194.08116" z="179.24924" mesh="ab_up3_lizard.cga" state="0xA" />
		<staticdoor keyid="185000058" doorid="3" x="525.20099" y="241.20856" z="179.16214" mesh="ab_up3_drakan.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="11" x="541.50482" y="881.35974" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000060" doorid="14" x="577.49182" y="845.16333" z="199.39857" mesh="ab_up3_door_04a.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="15" x="528.20135" y="883.72211" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="17" x="514.95459" y="881.43506" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="18" x="503.20822" y="874.72076" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="19" x="494.55392" y="864.5708" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="20" x="489.97031" y="851.83215" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="28" x="489.89212" y="838.30884" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="74" x="494.53024" y="825.64215" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="76" x="553.11902" y="874.65997" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="79" x="561.7348" y="864.30389" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
		<staticdoor keyid="185000059" doorid="80" x="566.28241" y="851.64075" z="199.61107" mesh="ab_up3_door_glass.cga" state="0xA" />
	</world>
	<world world="300150000">
		<staticdoor keyid="185000083" doorid="97" x="783.14557" y="412.0347" z="134.52167" mesh="door_temple2.cga" state="0xA" />
		<staticdoor doorid="99" x="772.60211" y="334.0856" z="139.04517" mesh="door_temple2.cga" state="0x8" />
		<staticdoor keyid="185000084" doorid="102" x="636.97766" y="574.40875" z="131.56458" mesh="door_temple1.cga" state="0xA" />
		<staticdoor keyid="185000085" doorid="121" x="505.32037" y="405.03531" z="136.99051" mesh="door_temple2.cga" state="0xA" />
	</world>
	<world world="300160000">
		<staticdoor keyid="185000087" doorid="100" x="537.74243" y="1244.3767" z="187.88522" mesh="door_temple7.cga" state="0xA" />
